export const REGISTER_REQUEST='REGISTER_REQUEST'
export const REGISTER_SUCCESS='REGISTER_SUCCESS'
export const REGISTER_FAILURE='REGISTER_FAILURE'

export const LOGIN_REQUEST='LOGIN_REQUEST'
export const LOGIN_SUCCESS='LOGIN_SUCCESS'
export const LOGIN_FAILURE='LOGIN_FAILURE'

export const GET_USER_REQUEST='GET_USER_REQUEST'
export const GET_USER_SUCCESS='GET_USER_SUCCESS'
export const GET_USER_FAILURE='GET_USER_FAILURE'

export const GET_ALL_CUSTOMERS_REQUEST = "GET_ALL_CUSTOMERS_REQUEST";
export const GET_ALL_CUSTOMERS_SUCCESS = "GET_ALL_CUSTOMERS_SUCCESS";
export const GET_ALL_CUSTOMERS_FAILURE = "GET_ALL_CUSTOMERS_FAILURE";

export const LOGOUT="LOGOUT"

export const FIND_PRODUCT_BY_ID_REQUEST="FIND_PRODUCT_BY_ID_REQUEST"
export const FIND_PRODUCT_BY_ID_SUCCESS="FIND_PRODUCT_BY_ID_SUCCESS"
export const FIND_PRODUCT_BY_ID_FAILURE="FIND_PRODUCT_BY_ID_FAILURE"

export const FIND_PRODUCTS_REQUEST="FIND_PRODUCTS_REQUEST"
export const FIND_PRODUCTS_SUCCESS="FIND_PRODUCTS_SUCCESS"
export const FIND_PRODUCTS_FAILURE="FIND_PRODUCTS_FAILURE"

export const FIND_PRODUCT_BY_CATEGORY_REQUEST="FIND_PRODUCT_BY_CATEGORY_REQUEST"
export const FIND_PRODUCT_BY_CATEGORY_SUCCESS="FIND_PRODUCT_BY_CATEGORY_SUCCESS"
export const FIND_PRODUCT_BY_CATEGORY_FAILURE="FIND_PRODUCT_BY_CATEGORY_FAILURE"

export const ADD_ITEM_TO_CART_REQUEST="ADD_ITEM_TO_CART_REQUEST"
export const ADD_ITEM_TO_CART_SUCCESS="ADD_ITEM_TO_CART_SUCCESS"
export const ADD_ITEM_TO_CART_FAILURE="ADD_ITEM_TO_CART_FAILURE"

export const GET_CART_REQUEST="GET_CART_REQUEST"
export const GET_CART_SUCCESS="GET_CART_SUCCESS"
export const GET_CART_FAILURE="GET_CART_FAILURE"

export const REMOVE_CART_ITEM_REQUEST="REMOVE_CART_ITEM_REQUEST"
export const REMOVE_CART_ITEM_SUCCESS="REMOVE_CART_ITEM_SUCCESS"
export const REMOVE_CART_ITEM_FAILURE="REMOVE_CART_ITEM_FAILURE"

export const UPDATE_CART_ITEM_REQUEST="UPDATE_CART_ITEM_REQUEST"
export const UPDATE_CART_ITEM_SUCCESS="UPDATE_CART_ITEM_SUCCESS"
export const UPDATE_CART_ITEM_FAILURE="UPDATE_CART_ITEM_FAILURE"

export const CREATE_ORDER_REQUEST="CREATE_ORDER_REQUEST"
export const CREATE_ORDER_SUCCESS="CREATE_ORDER_SUCCESS"
export const CREATE_ORDER_FAILURE="CREATE_ORDER_FAILURE"

export const GET_ORDER_BY_ID_REQUEST="GET_ORDER_BY_ID_REQUEST"
export const GET_ORDER_BY_ID_SUCCESS="GET_ORDER_BY_ID_SUCCESS"
export const GET_ORDER_BY_ID_FAILURE="GET_ORDER_BY_ID_FAILURE"

export const GET_ORDER_HISTORY_REQUEST="GET_ORDER_HISTORY_REQUEST"
export const GET_ORDER_HISTORY_SUCCESS="GET_ORDER_HISTORY_SUCCESS"
export const GET_ORDER_HISTORY_FAILURE="GET_ORDER_HISTORY_FAILURE"

export const CREATE_PAYMENT_REQUEST="CREATE_PAYMENT_REQUEST"
export const CREATE_PAYMENT_SUCCESS="CREATE_PAYMENT_SUCCESS"
export const CREATE_PAYMENT_FAILURE="CREATE_PAYMENT_FAILURE"

export const UPDATE_PAYMENT_REQUEST="UPDATE_PAYMENT_REQUEST"
export const UPDATE_PAYMENT_SUCCESS="UPDATE_PAYMENT_SUCCESS"
export const UPDATE_PAYMENT_FAILURE="UPDATE_PAYMENT_FAILURE"

export const GET_PRODUCT_REQUEST="GET_PRODUCT_REQUEST"
export const GET_PRODUCT_SUCCESS="GET_PRODUCT_SUCCESS"
export const GET_PRODUCT_FAILURE="GET_PRODUCT_FAILURE"

export const DELETE_PRODUCT_REQUEST='DELETE_PRODUCT_REQUEST'
export const DELETE_PRODUCT_SUCCESS='DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_FAILURE='DELETE_PRODUCT_FAILURE'

export const CREATE_PRODUCT_REQUEST='CREATE_PRODUCT_REQUEST'
export const CREATE_PRODUCT_SUCCESS='CREATE_PRODUCT_SUCCESS'
export const CREATE_PRODUCT_FAILURE='CREATE_PRODUCT_FAILURE'

export const GET_ORDERS_REQUEST = 'GET_ORDERS_REQUEST';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAILURE = 'GET_ORDERS_FAILURE';

// Action types for confirmed order
export const CONFIRMED_ORDER_REQUEST = 'CONFIRMED_ORDER_REQUEST';
export const CONFIRMED_ORDER_SUCCESS = 'CONFIRMED_ORDER_SUCCESS';
export const CONFIRMED_ORDER_FAILURE = 'CONFIRMED_ORDER_FAILURE';

// Action types for placed order
export const PLACED_ORDER_REQUEST = 'PLACED_ORDER_REQUEST';
export const PLACED_ORDER_SUCCESS = 'PLACED_ORDER_SUCCESS';
export const PLACED_ORDER_FAILURE = 'PLACED_ORDER_FAILURE';

// Action types for delivered order
export const DELIVERED_ORDER_REQUEST = 'DELIVERED_ORDER_REQUEST';
export const DELIVERED_ORDER_SUCCESS = 'DELIVERED_ORDER_SUCCESS';
export const DELIVERED_ORDER_FAILURE = 'DELIVERED_ORDER_FAILURE';

// Action types for canceled order
export const CANCELED_ORDER_REQUEST = 'CANCELED_ORDER_REQUEST';
export const CANCELED_ORDER_SUCCESS = 'CANCELED_ORDER_SUCCESS';
export const CANCELED_ORDER_FAILURE = 'CANCELED_ORDER_FAILURE';

// Action types for deleting an order
export const DELETE_ORDER_REQUEST = 'DELETE_ORDER_REQUEST';
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS';
export const DELETE_ORDER_FAILURE = 'DELETE_ORDER_FAILURE';

// actionTypes.js for shipped order
export const SHIP_ORDER_REQUEST = 'SHIP_ORDER_REQUEST';
export const SHIP_ORDER_SUCCESS = 'SHIP_ORDER_SUCCESS';
export const SHIP_ORDER_FAILURE = 'SHIP_ORDER_FAILURE';

export const GET_ALL_PRODUCTS_REQUEST = 'GET_ALL_PRODUCTS_REQUEST';
export const GET_ALL_PRODUCTS_SUCCESS = 'GET_ALL_PRODUCTS_SUCCESS';
export const GET_ALL_PRODUCTS_FAILURE = 'GET_ALL_PRODUCTS_FAILURE';

export const CHANGE_NUMBER_REQUEST="CHANGE_NUMBER_REQUEST"
export const CHANGE_NUMBER_SUCCESS="CHANGE_NUMBER_SUCCESS"
export const CHANGE_NUMBER_FAILURE="CHANGE_NUMBER_FAILURE"











